version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./rss:/app/rss/
      - ./db.json:/app/db.json
      - ./current.session:/app/current.session
